import _ from "lodash";

export var langList = {
  Afrikaans: "af",
  Albanian: "sq",
  Amharic: "am",
  Arabic: "ar",
  Armenian: "hy",
  Assamese: "as",
  Aymara: "ay",
  Azerbaijani: "az",
  Bambara: "bm",
  Basque: "eu",
  Belarusian: "be",
  Bengali: "bn",
  Bhojpuri: "bho",
  Bosnian: "bs",
  Bulgarian: "bg",
  Catalan: "ca",
  Cebuano: "ceb",
  ChineseSimplified: "zh-CN",
  ChineseTraditional: "zh-TW",
  Corsican: "co",
  Croatian: "hr",
  Czech: "cs",
  Danish: "da",
  Dhivehi: "dv",
  Dogri: "doi",
  Dutch: "nl",
  English: "en",
  Esperanto: "eo",
  Estonian: "et",
  Ewe: "ee",
  Filipino: "tl",
  Finnish: "fi",
  French: "fr",
  Frisian: "fy",
  Galician: "gl",
  Georgian: "ka",
  German: "de",
  Greek: "el",
  Guarani: "gn",
  Gujarati: "gu",
  HaitianCreole: "ht",
  Hausa: "ha",
  Hawaiian: "haw",
  Hebrew: "iw",
  Hindi: "hi",
  Hmong: "hmn",
  Hungarian: "hu",
  Icelandic: "is",
  Igbo: "ig",
  Ilocano: "ilo",
  Indonesian: "id",
  Irish: "ga",
  Italian: "it",
  Japanese: "ja",
  Javanese: "jw",
  Kannada: "kn",
  Kazakh: "kk",
  Khmer: "km",
  Kinyarwanda: "rw",
  Konkani: "gom",
  Korean: "ko",
  Krio: "kri",
  Kurdish: "ku",
  KurdishSorani: "ckb",
  Kyrgyz: "ky",
  Lao: "lo",
  Latin: "la",
  Latvian: "lv",
  Lingala: "ln",
  Lithuanian: "lt",
  Luganda: "lg",
  Luxembourgish: "lb",
  Macedonian: "mk",
  Maithili: "mai",
  Malagasy: "mg",
  Malay: "ms",
  Malayalam: "ml",
  Maltese: "mt",
  Maori: "mi",
  Marathi: "mr",
  // Meiteilon: "mni-Mtei",
  Mizo: "lus",
  Mongolian: "mn",
  Myanmar: "my",
  Nepali: "ne",
  Norwegian: "no",
  Nyanja: "ny",
  Odia: "or",
  Oromo: "om",
  Pashto: "ps",
  Persian: "fa",
  Polish: "pl",
  Portuguese: "pt",
  Punjabi: "pa",
  Quechua: "qu",
  Romanian: "ro",
  Russian: "ru",
  Samoan: "sm",
  Sanskrit: "sa",
  ScotsGaelic: "gd",
  Sepedi: "nso",
  Serbian: "sr",
  Sesotho: "st",
  Shona: "sn",
  Sindhi: "sd",
  Sinhala: "si",
  Slovak: "sk",
  Slovenian: "sl",
  Somali: "so",
  Spanish: "es",
  Sundanese: "su",
  Swahili: "sw",
  Swedish: "sv",
  Tajik: "tg",
  Tamil: "ta",
  Tatar: "tt",
  Telugu: "te",
  Thai: "th",
  Tigrinya: "ti",
  Tsonga: "ts",
  Turkish: "tr",
  Turkmen: "tk",
  Twi: "ak",
  Ukrainian: "uk",
  Urdu: "ur",
  Uyghur: "ug",
  Uzbek: "uz",
  Vietnamese: "vi",
  Welsh: "cy",
  Xhosa: "xh",
  Yiddish: "yi",
  Yoruba: "yo",
  Zulu: "zu",
};

export var langListOpposite = _.invert(langList);

export var rtlLangList = [
  "ar", ///Arabic
  "az", ///Azerbaijani
  "bm", ///Bambara
  "dv", ///Dhivehi
  "doi", ///Dogri
  "ha", ///Hausa
  "iw", ///Hebrew
  "kk", ///Kazakh
  "ku", ///Kurdish
  "ckb", ///Kurdish Sorani
  "ky", ///Kyrgyz
  "ml", ///Malayalam
  "ps", ///Pashto
  "fa", ///Persian
  "sd", ///Sindhi
  "so", ///Somali
  "su", ///Sundanese
  "tg", ///Tajik
  "tk", ///Turkmen
  "ur", ///Urdu
  "ug", ///Uyghur
  "uz", ///Uzbek
  "yi", ///Yiddish
  "yo", ///Yoruba
]; //right to left language system list

export var bingTtsVoiceList = {
  af: ["af-ZA-AdriNeural", "af-ZA-WillemNeural"],
  sq: ["sq-AL-AnilaNeural", "sq-AL-IlirNeural"],
  am: ["am-ET-AmehaNeural", "am-ET-MekdesNeural"],
  ar: [
    "ar-DZ-AminaNeural",
    "ar-DZ-IsmaelNeural",
    "ar-BH-AliNeural",
    "ar-BH-LailaNeural",
    "ar-EG-SalmaNeural",
    "ar-EG-ShakirNeural",
    "ar-IQ-BasselNeural",
    "ar-IQ-RanaNeural",
    "ar-JO-SanaNeural",
    "ar-JO-TaimNeural",
    "ar-KW-FahedNeural",
    "ar-KW-NouraNeural",
    "ar-LB-LaylaNeural",
    "ar-LB-RamiNeural",
    "ar-LY-ImanNeural",
    "ar-LY-OmarNeural",
    "ar-MA-JamalNeural",
    "ar-MA-MounaNeural",
    "ar-OM-AbdullahNeural",
    "ar-OM-AyshaNeural",
    "ar-QA-AmalNeural",
    "ar-QA-MoazNeural",
    "ar-SA-HamedNeural",
    "ar-SA-ZariyahNeural",
    "ar-SY-AmanyNeural",
    "ar-SY-LaithNeural",
    "ar-TN-HediNeural",
    "ar-TN-ReemNeural",
    "ar-AE-FatimaNeural",
    "ar-AE-HamdanNeural",
    "ar-YE-MaryamNeural",
    "ar-YE-SalehNeural",
  ],
  az: ["az-AZ-BabekNeural", "az-AZ-BanuNeural"],
  bn: [
    "bn-BD-NabanitaNeural",
    "bn-BD-PradeepNeural",
    "bn-IN-BashkarNeural",
    "bn-IN-TanishaaNeural",
  ],
  bs: ["bs-BA-GoranNeural", "bs-BA-VesnaNeural"],
  bg: ["bg-BG-BorislavNeural", "bg-BG-KalinaNeural"],
  my: ["my-MM-NilarNeural", "my-MM-ThihaNeural"],
  ca: ["ca-ES-EnricNeural", "ca-ES-JoanaNeural"],
  "zh-HK": [
    "zh-HK-HiuGaaiNeural",
    "zh-HK-HiuMaanNeural",
    "zh-HK-WanLungNeural",
  ],
  "zh-CN": [
    "zh-CN-XiaoxiaoNeural",
    "zh-CN-XiaoyiNeural",
    "zh-CN-YunjianNeural",
    "zh-CN-YunxiNeural",
    "zh-CN-YunxiaNeural",
    "zh-CN-YunyangNeural",
  ],
  "zh-CN-liaoning": ["zh-CN-liaoning-XiaobeiNeural"],
  "zh-TW": [
    "zh-TW-HsiaoChenNeural",
    "zh-TW-YunJheNeural",
    "zh-TW-HsiaoYuNeural",
  ],
  "zh-CN-shaanxi": ["zh-CN-shaanxi-XiaoniNeural"],
  hr: ["hr-HR-GabrijelaNeural", "hr-HR-SreckoNeural"],
  cs: ["cs-CZ-AntoninNeural", "cs-CZ-VlastaNeural"],
  da: ["da-DK-ChristelNeural", "da-DK-JeppeNeural"],
  nl: [
    "nl-BE-ArnaudNeural",
    "nl-BE-DenaNeural",
    "nl-NL-ColetteNeural",
    "nl-NL-FennaNeural",
    "nl-NL-MaartenNeural",
  ],
  en: [
    "en-AU-NatashaNeural",
    "en-AU-WilliamNeural",
    "en-CA-ClaraNeural",
    "en-CA-LiamNeural",
    "en-HK-SamNeural",
    "en-HK-YanNeural",
    "en-IN-NeerjaNeural",
    "en-IN-NeerjaNeural",
    "en-IN-PrabhatNeural",
    "en-IE-ConnorNeural",
    "en-IE-EmilyNeural",
    "en-KE-AsiliaNeural",
    "en-KE-ChilembaNeural",
    "en-NZ-MitchellNeural",
    "en-NZ-MollyNeural",
    "en-NG-AbeoNeural",
    "en-NG-EzinneNeural",
    "en-PH-JamesNeural",
    "en-PH-RosaNeural",
    "en-SG-LunaNeural",
    "en-SG-WayneNeural",
    "en-ZA-LeahNeural",
    "en-ZA-LukeNeural",
    "en-TZ-ElimuNeural",
    "en-TZ-ImaniNeural",
    "en-GB-LibbyNeural",
    "en-GB-MaisieNeural",
    "en-GB-RyanNeural",
    "en-GB-SoniaNeural",
    "en-GB-ThomasNeural",
    "en-US-AriaNeural",
    "en-US-AnaNeural",
    "en-US-ChristopherNeural",
    "en-US-EricNeural",
    "en-US-GuyNeural",
    "en-US-JennyNeural",
    "en-US-MichelleNeural",
    "en-US-RogerNeural",
    "en-US-SteffanNeural",
  ],
  et: ["et-EE-AnuNeural", "et-EE-KertNeural"],
  tl: ["fil-PH-AngeloNeural", "fil-PH-BlessicaNeural"],
  fi: ["fi-FI-HarriNeural", "fi-FI-NooraNeural"],
  fr: [
    "fr-BE-CharlineNeural",
    "fr-BE-GerardNeural",
    "fr-CA-AntoineNeural",
    "fr-CA-JeanNeural",
    "fr-CA-SylvieNeural",
    "fr-FR-DeniseNeural",
    "fr-FR-EloiseNeural",
    "fr-FR-HenriNeural",
    "fr-CH-ArianeNeural",
    "fr-CH-FabriceNeural",
  ],
  gl: ["gl-ES-RoiNeural", "gl-ES-SabelaNeural"],
  ka: ["ka-GE-EkaNeural", "ka-GE-GiorgiNeural"],
  de: [
    "de-AT-IngridNeural",
    "de-AT-JonasNeural",
    "de-DE-AmalaNeural",
    "de-DE-ConradNeural",
    "de-DE-KatjaNeural",
    "de-DE-KillianNeural",
    "de-CH-JanNeural",
    "de-CH-LeniNeural",
  ],
  el: ["el-GR-AthinaNeural", "el-GR-NestorasNeural"],
  gu: ["gu-IN-DhwaniNeural", "gu-IN-NiranjanNeural"],
  iw: ["he-IL-AvriNeural", "he-IL-HilaNeural"],
  hi: ["hi-IN-MadhurNeural", "hi-IN-SwaraNeural"],
  hu: ["hu-HU-NoemiNeural", "hu-HU-TamasNeural"],
  is: ["is-IS-GudrunNeural", "is-IS-GunnarNeural"],
  id: ["id-ID-ArdiNeural", "id-ID-GadisNeural"],
  ga: ["ga-IE-ColmNeural", "ga-IE-OrlaNeural"],
  it: ["it-IT-DiegoNeural", "it-IT-ElsaNeural", "it-IT-IsabellaNeural"],
  ja: ["ja-JP-KeitaNeural", "ja-JP-NanamiNeural"],
  jv: ["jv-ID-DimasNeural", "jv-ID-SitiNeural"],
  kn: ["kn-IN-GaganNeural", "kn-IN-SapnaNeural"],
  kk: ["kk-KZ-AigulNeural", "kk-KZ-DauletNeural"],
  km: ["km-KH-PisethNeural", "km-KH-SreymomNeural"],
  ko: ["ko-KR-InJoonNeural", "ko-KR-SunHiNeural"],
  lo: ["lo-LA-ChanthavongNeural", "lo-LA-KeomanyNeural"],
  lv: ["lv-LV-EveritaNeural", "lv-LV-NilsNeural"],
  lt: ["lt-LT-LeonasNeural", "lt-LT-OnaNeural"],
  mk: ["mk-MK-AleksandarNeural", "mk-MK-MarijaNeural"],
  ms: ["ms-MY-OsmanNeural", "ms-MY-YasminNeural"],
  ml: ["ml-IN-MidhunNeural", "ml-IN-SobhanaNeural"],
  mt: ["mt-MT-GraceNeural", "mt-MT-JosephNeural"],
  mr: ["mr-IN-AarohiNeural", "mr-IN-ManoharNeural"],
  mn: ["mn-MN-BataaNeural", "mn-MN-YesuiNeural"],
  ne: ["ne-NP-HemkalaNeural", "ne-NP-SagarNeural"],
  nb: ["nb-NO-FinnNeural", "nb-NO-PernilleNeural"],
  ps: ["ps-AF-GulNawazNeural", "ps-AF-LatifaNeural"],
  fa: ["fa-IR-DilaraNeural", "fa-IR-FaridNeural"],
  pl: ["pl-PL-MarekNeural", "pl-PL-ZofiaNeural"],
  pt: [
    "pt-BR-AntonioNeural",
    "pt-BR-FranciscaNeural",
    "pt-PT-DuarteNeural",
    "pt-PT-RaquelNeural",
  ],
  ro: ["ro-RO-AlinaNeural", "ro-RO-EmilNeural"],
  ru: ["ru-RU-DmitryNeural", "ru-RU-SvetlanaNeural"],
  sr: ["sr-RS-NicholasNeural", "sr-RS-SophieNeural"],
  si: ["si-LK-SameeraNeural", "si-LK-ThiliniNeural"],
  sk: ["sk-SK-LukasNeural", "sk-SK-ViktoriaNeural"],
  sl: ["sl-SI-PetraNeural", "sl-SI-RokNeural"],
  so: ["so-SO-MuuseNeural", "so-SO-UbaxNeural"],
  es: [
    "es-AR-ElenaNeural",
    "es-AR-TomasNeural",
    "es-BO-MarceloNeural",
    "es-BO-SofiaNeural",
    "es-CL-CatalinaNeural",
    "es-CL-LorenzoNeural",
    "es-CO-GonzaloNeural",
    "es-CO-SalomeNeural",
    "es-CR-JuanNeural",
    "es-CR-MariaNeural",
    "es-CU-BelkysNeural",
    "es-CU-ManuelNeural",
    "es-DO-EmilioNeural",
    "es-DO-RamonaNeural",
    "es-EC-AndreaNeural",
    "es-EC-LuisNeural",
    "es-SV-LorenaNeural",
    "es-SV-RodrigoNeural",
    "es-GQ-JavierNeural",
    "es-GQ-TeresaNeural",
    "es-GT-AndresNeural",
    "es-GT-MartaNeural",
    "es-HN-CarlosNeural",
    "es-HN-KarlaNeural",
    "es-MX-DaliaNeural",
    "es-MX-JorgeNeural",
    "es-NI-FedericoNeural",
    "es-NI-YolandaNeural",
    "es-PA-MargaritaNeural",
    "es-PA-RobertoNeural",
    "es-PY-MarioNeural",
    "es-PY-TaniaNeural",
    "es-PE-AlexNeural",
    "es-PE-CamilaNeural",
    "es-PR-KarinaNeural",
    "es-PR-VictorNeural",
    "es-ES-AlvaroNeural",
    "es-ES-ElviraNeural",
    "es-US-AlonsoNeural",
    "es-US-PalomaNeural",
    "es-UY-MateoNeural",
    "es-UY-ValentinaNeural",
    "es-VE-PaolaNeural",
    "es-VE-SebastianNeural",
  ],
  su: ["su-ID-JajangNeural", "su-ID-TutiNeural"],
  sw: [
    "sw-KE-RafikiNeural",
    "sw-KE-ZuriNeural",
    "sw-TZ-DaudiNeural",
    "sw-TZ-RehemaNeural",
  ],
  sv: ["sv-SE-MattiasNeural", "sv-SE-SofieNeural"],
  ta: [
    "ta-IN-PallaviNeural",
    "ta-IN-ValluvarNeural",
    "ta-MY-KaniNeural",
    "ta-MY-SuryaNeural",
    "ta-SG-AnbuNeural",
    "ta-SG-VenbaNeural",
    "ta-LK-KumarNeural",
    "ta-LK-SaranyaNeural",
  ],
  te: ["te-IN-MohanNeural", "te-IN-ShrutiNeural"],
  th: ["th-TH-NiwatNeural", "th-TH-PremwadeeNeural"],
  tr: ["tr-TR-AhmetNeural", "tr-TR-EmelNeural"],
  uk: ["uk-UA-OstapNeural", "uk-UA-PolinaNeural"],
  ur: [
    "ur-IN-GulNeural",
    "ur-IN-SalmanNeural",
    "ur-PK-AsadNeural",
    "ur-PK-UzmaNeural",
  ],
  uz: ["uz-UZ-MadinaNeural", "uz-UZ-SardorNeural"],
  vi: ["vi-VN-HoaiMyNeural", "vi-VN-NamMinhNeural"],
  cy: ["cy-GB-AledNeural", "cy-GB-NiaNeural"],
  zu: ["zu-ZA-ThandoNeural", "zu-ZA-ThembaNeural"],
};

export var googleTranslateTtsLangList = [
  "af",
  "sq",
  "ar",
  "bn",
  "bs",
  "bg",
  "ca",
  "zh-CN",
  "zh-TW",
  "hr",
  "cs",
  "da",
  "nl",
  "en",
  "et",
  "tl",
  "fi",
  "fr",
  "de",
  "el",
  "gu",
  "iw",
  "hi",
  "hu",
  "is",
  "id",
  "it",
  "ja",
  "jw",
  "kn",
  "km",
  "ko",
  "la",
  "lv",
  "ms",
  "ml",
  "mr",
  "my",
  "ne",
  "no",
  "pl",
  "pt",
  "ro",
  "ru",
  "sr",
  "si",
  "sk",
  "es",
  "su",
  "sw",
  "sv",
  "ta",
  "te",
  "th",
  "tr",
  "uk",
  "ur",
  "vi",
];

export var ocrLangList = {
  Afrikaans: "afr",
  Albanian: "sqi",
  Amharic: "amh",
  Arabic: "ara",
  Armenian: "hye",
  Azerbaijani: "aze",
  Basque: "eus",
  Belarusian: "bel",
  Bengali: "ben",
  Bosnian: "bos",
  Bulgarian: "bul",
  Burmese: "mya",
  Catalan: "cat",
  Cebuano: "ceb",
  "Chinese Simplified": "chi_sim",
  "Chinese Simplified (vertical)": "chi_sim_vert",
  "Chinese Traditional": "chi_tra",
  "Chinese Traditional (vertical)": "chi_tra_vert",
  Corsican: "cos",
  Croatian: "hrv",
  Czech: "ces",
  Danish: "dan",
  Dutch: "nld",
  English: "eng",
  Esperanto: "epo",
  Estonian: "est",
  Filipino: "fil",
  Finnish: "fin",
  French: "fra",
  Frisian: "fry",
  Galician: "glg",
  Georgian: "kat",
  German: "deu",
  Greek: "ell",
  Gujarati: "guj",
  Haitian: "hat",
  Hebrew: "heb",
  Hindi: "hin",
  Hungarian: "hun",
  Icelandic: "isl",
  Indonesian: "ind",
  Irish: "gle",
  Italian: "ita",
  Japanese: "jpn",
  "Japanese (vertical)": "jpn_vert",
  Javanese: "jav",
  Kannada: "kan",
  Kazakh: "kaz",
  Khmer: "khm",
  Korean: "kor",
  "Korean (vertical)": "kor_vert",
  Kurdish: "kmr",
  Lao: "lao",
  Latin: "lat",
  Latvian: "lav",
  Lithuanian: "lit",
  Luxembourgish: "ltz",
  Macedonian: "mkd",
  Malay: "msa",
  Malayalam: "mal",
  Maltese: "mlt",
  Maori: "mri",
  Marathi: "mar",
  Mongolian: "mon",
  Nepali: "nep",
  Norwegian: "nor",
  Persian: "fas",
  Polish: "pol",
  Portuguese: "por",
  Romanian: "ron",
  Russian: "rus",
  "Scottish Gaelic": "gla",
  Serbian: "srp",
  Sindhi: "snd",
  Sinhala: "sin",
  Slovak: "slk",
  Slovenian: "slv",
  Spanish: "spa",
  Sundanese: "sun",
  Swahili: "swa",
  Swedish: "swe",
  Tajik: "tgk",
  Tamil: "tam",
  Telugu: "tel",
  Thai: "tha",
  Turkish: "tur",
  Ukrainian: "ukr",
  Urdu: "urd",
  Uzbek: "uzb",
  Vietnamese: "vie",
  Welsh: "cym",
  Yiddish: "yid",
  Yoruba: "yor",
};

export var listenLangList = {
  Afrikaans: "af-ZA",
  Amharic: "am-ET",
  "Arabic_Uni Arab Emirates": "ar-AE",
  Arabic_Bahrain: "ar-BH",
  Arabic_Algeria: "ar-DZ",
  Arabic_Egypt: "ar-EG",
  Arabic_Iraq: "ar-IQ",
  Arabic_Jordan: "ar-JO",
  Arabic_Kuwait: "ar-KW",
  Arabic_Lebanon: "ar-LB",
  Arabic_Libya: "ar-LY",
  Arabic_Maroco: "ar-MA",
  Arabic_Oman: "ar-OM",
  Arabic_Qatar: "ar-QA",
  "Arabic_Saudi Arabia": "ar-SA",
  Arabic_Syria: "ar-SY",
  Arabic_Tunisia: "ar-TN",
  Arabic_Yemen: "ar-YE",
  Armenian: "hy-AM",
  Azerbaijani: "az-AZ",
  Bangla_Bangladesh: "bn-BD",
  Bangla_India: "bn-IN",
  Basque: "eu-ES",
  Bulgarian: "bg-BG",
  Catalan: "ca-ES",
  "Chinese_Chinese Mandarin (Mainland China)": "cmn-Hans-CN",
  "Chinese_Chinese Mandarin (Hongkong)": "cmn-Hans-HK",
  "Chinese_Chinese (Taiwan)": "cmn-Hant-TW",
  "Chinese_Chinese Cantonese (Hongkong)": "yue-Hant-HK",
  Croatian: "hr-HR",
  Czech: "cs-CZ",
  Dansk: "da-DK",
  Deutsch: "de-DE",
  Dutch: "nl-NL",
  English_Australia: "en-AU",
  English_Canada: "en-CA",
  English_India: "en-IN",
  English_Kenya: "en-KE",
  English_Tanzania: "en-TZ",
  English_Ghana: "en-GH",
  "English_New Zealand": "en-NZ",
  English_Nigeria: "en-NG",
  "English_South Africa": "en-ZA",
  English_Philippines: "en-PH",
  "English_United Kingdom": "en-GB",
  "English_United States": "en-US",
  Filipino: "fil-PH",
  Finland: "fi-FI",
  French: "fr-FR",
  Galician: "gl-ES",
  Georgian: "ka-GE",
  Greek: "el-GR",
  Gujarati: "gu-IN",
  Hindi: "hi-IN",
  Hungarian: "hu-HU",
  Icelandic: "is-IS",
  Indonesian: "id-ID",
  Italian_Italia: "it-IT",
  Italian_Svizzera: "it-CH",
  Japanese: "ja-JP",
  Javanese: "jv-ID",
  Kannada: "kn-IN",
  Khmer: "km-KH",
  Kiswahili_Tanzania: "sw-TZ",
  Kiswahili_Kenya: "sw-KE",
  Korean: "ko-KR",
  Lao: "lo-LA",
  Latvian: "lv-LV",
  Lithuanian: "lt-LT",
  Malay: "ms-MY",
  Malayalam: "ml-IN",
  Marathi: "mr-IN",
  Myanmar: "my-MM",
  Nepali: "ne-NP",
  "Norwegian Bokmål": "nb-NO",
  Polish: "pl-PL",
  Portuguese_Brasil: "pt-BR",
  Portuguese_Portugal: "pt-PT",
  Romania: "ro-RO",
  Russian: "ru-RU",
  Serbian: "sr-RS",
  Sinhala: "si-LK",
  Slovene: "sl-SI",
  Slovak: "sk-SK",
  Spanish_Argentina: "es-AR",
  Spanish_Bolivia: "es-BO",
  Spanish_Chile: "es-CL",
  Spanish_Colombia: "es-CO",
  "Spanish_Costa Rica": "es-CR",
  Spanish_Ecuador: "es-EC",
  "Spanish_El Salvador": "es-SV",
  Spanish_España: "es-ES",
  "Spanish_Estados Unidos": "es-US",
  Spanish_Guatemala: "es-GT",
  Spanish_Honduras: "es-HN",
  Spanish_México: "es-MX",
  Spanish_Nicaragua: "es-NI",
  Spanish_Panamá: "es-PA",
  Spanish_Paraguay: "es-PY",
  Spanish_Perú: "es-PE",
  "Spanish_Puerto Rico": "es-PR",
  "Spanish_República Dominicana": "es-DO",
  Spanish_Uruguay: "es-UY",
  Spanish_Venezuela: "es-VE",
  Sundanese: "su-ID",
  Swedish_undefined: "sv-SE",
  Swedish_Kenya: "sw-KE",
  Tamil_India: "ta-IN",
  Tamil_Singapore: "ta-SG",
  "Tamil_Sri Lanka": "ta-LK",
  Tamil_Malaysia: "ta-MY",
  Telugu: "te-IN",
  Thai: "th-TH",
  Turkish: "tr-TR",
  Urdu_Pakistan: "ur-PK",
  Urdu_India: "ur-IN",
  Vietnamese: "vi-VN",
  Ukrainian: "uk-UA",
  Zulu: "zu-ZA",
};


export var navigatorLangToISO ={
    "af": "af",
    "af-NA": "af",
    "af-ZA": "af",
    "ak": "ak",
    "ak-GH": "ak",
    "am": "am",
    "am-ET": "am",
    "ar": "ar",
    "ar-001": "ar",
    "ar-AE": "ar",
    "ar-BH": "ar",
    "ar-DJ": "ar",
    "ar-DZ": "ar",
    "ar-EG": "ar",
    "ar-EH": "ar",
    "ar-ER": "ar",
    "ar-IL": "ar",
    "ar-IQ": "ar",
    "ar-JO": "ar",
    "ar-KM": "ar",
    "ar-KW": "ar",
    "ar-LB": "ar",
    "ar-LY": "ar",
    "ar-MA": "ar",
    "ar-MR": "ar",
    "ar-OM": "ar",
    "ar-PS": "ar",
    "ar-QA": "ar",
    "ar-SA": "ar",
    "ar-SD": "ar",
    "ar-SO": "ar",
    "ar-SS": "ar",
    "ar-SY": "ar",
    "ar-TD": "ar",
    "ar-TN": "ar",
    "ar-YE": "ar",
    "as": "as",
    "as-IN": "as",
    "az": "az",
    "az-Cyrl": "az",
    "az-Cyrl-AZ": "az",
    "az-Latn": "az",
    "az-Latn-AZ": "az",
    "be": "be",
    "be-BY": "be",
    "bem": "bem",
    "bem-ZM": "bem",
    "bg": "bg",
    "bg-BG": "bg",
    "bm": "bm",
    "bm-ML": "bm",
    "bn": "bn",
    "bn-BD": "bn",
    "bn-IN": "bn",
    "bo": "bo",
    "bo-CN": "bo",
    "bo-IN": "bo",
    "br": "br",
    "br-FR": "br",
    "bs": "bs",
    "bs-Cyrl": "bs",
    "bs-Cyrl-BA": "bs",
    "bs-Latn": "bs",
    "bs-Latn-BA": "bs",
    "ca": "ca",
    "ca-AD": "ca",
    "ca-ES": "ca",
    "ca-FR": "ca",
    "ca-IT": "ca",
    "cs": "cs",
    "cs-CZ": "cs",
    "cy": "cy",
    "cy-GB": "cy",
    "da": "da",
    "da-DK": "da",
    "da-GL": "da",
    "de": "de",
    "de-AT": "de",
    "de-BE": "de",
    "de-CH": "de",
    "de-DE": "de",
    "de-IT": "de",
    "de-LI": "de",
    "de-LU": "de",
    "dz": "dz",
    "dz-BT": "dz",
    "ee": "ee",
    "ee-GH": "ee",
    "ee-TG": "ee",
    "el": "el",
    "el-CY": "el",
    "el-GR": "el",
    "en": "en",
    "en-001": "en",
    "en-150": "en",
    "en-AG": "en",
    "en-AI": "en",
    "en-AS": "en",
    "en-AT": "en",
    "en-AU": "en",
    "en-BB": "en",
    "en-BE": "en",
    "en-BI": "en",
    "en-BM": "en",
    "en-BS": "en",
    "en-BW": "en",
    "en-BZ": "en",
    "en-CA": "en",
    "en-CC": "en",
    "en-CH": "en",
    "en-CK": "en",
    "en-CM": "en",
    "en-CX": "en",
    "en-CY": "en",
    "en-DE": "en",
    "en-DG": "en",
    "en-DK": "en",
    "en-DM": "en",
    "en-ER": "en",
    "en-FI": "en",
    "en-FJ": "en",
    "en-FK": "en",
    "en-FM": "en",
    "en-GB": "en",
    "en-GD": "en",
    "en-GG": "en",
    "en-GH": "en",
    "en-GI": "en",
    "en-GM": "en",
    "en-GU": "en",
    "en-GY": "en",
    "en-HK": "en",
    "en-IE": "en",
    "en-IL": "en",
    "en-IM": "en",
    "en-IN": "en",
    "en-IO": "en",
    "en-JE": "en",
    "en-JM": "en",
    "en-KE": "en",
    "en-KI": "en",
    "en-KN": "en",
    "en-KY": "en",
    "en-LC": "en",
    "en-LR": "en",
    "en-LS": "en",
    "en-MG": "en",
    "en-MH": "en",
    "en-MO": "en",
    "en-MP": "en",
    "en-MS": "en",
    "en-MT": "en",
    "en-MU": "en",
    "en-MW": "en",
    "en-MY": "en",
    "en-NA": "en",
    "en-NF": "en",
    "en-NG": "en",
    "en-NL": "en",
    "en-NR": "en",
    "en-NU": "en",
    "en-NZ": "en",
    "en-PG": "en",
    "en-PH": "en",
    "en-PK": "en",
    "en-PN": "en",
    "en-PR": "en",
    "en-PW": "en",
    "en-RW": "en",
    "en-SB": "en",
    "en-SC": "en",
    "en-SD": "en",
    "en-SE": "en",
    "en-SG": "en",
    "en-SH": "en",
    "en-SI": "en",
    "en-SL": "en",
    "en-SS": "en",
    "en-SX": "en",
    "en-SZ": "en",
    "en-TC": "en",
    "en-TK": "en",
    "en-TO": "en",
    "en-TT": "en",
    "en-TV": "en",
    "en-TZ": "en",
    "en-UG": "en",
    "en-UM": "en",
    "en-US": "en",
    "en-US-POSIX": "en",
    "en-VC": "en",
    "en-VG": "en",
    "en-VI": "en",
    "en-VU": "en",
    "en-WS": "en",
    "en-ZA": "en",
    "en-ZM": "en",
    "en-ZW": "en",
    "eo": "eo",
    "es": "es",
    "es-419": "es",
    "es-AR": "es",
    "es-BO": "es",
    "es-BR": "es",
    "es-BZ": "es",
    "es-CL": "es",
    "es-CO": "es",
    "es-CR": "es",
    "es-CU": "es",
    "es-DO": "es",
    "es-EA": "es",
    "es-EC": "es",
    "es-ES": "es",
    "es-GQ": "es",
    "es-GT": "es",
    "es-HN": "es",
    "es-IC": "es",
    "es-MX": "es",
    "es-NI": "es",
    "es-PA": "es",
    "es-PE": "es",
    "es-PH": "es",
    "es-PR": "es",
    "es-PY": "es",
    "es-SV": "es",
    "es-US": "es",
    "es-UY": "es",
    "es-VE": "es",
    "et": "et",
    "et-EE": "et",
    "eu": "eu",
    "eu-ES": "eu",
    "fa": "fa",
    "fa-AF": "fa",
    "fa-IR": "fa",
    "ff": "ff",
    "ff-CM": "ff",
    "ff-GN": "ff",
    "ff-MR": "ff",
    "ff-SN": "ff",
    "fi": "fi",
    "fi-FI": "fi",
    "fil": "tl",
    "fil-PH": "tl",
    "fo": "fo",
    "fo-DK": "fo",
    "fo-FO": "fo",
    "fr": "fr",
    "fr-BE": "fr",
    "fr-BF": "fr",
    "fr-BI": "fr",
    "fr-BJ": "fr",
    "fr-BL": "fr",
    "fr-CA": "fr-CA",
    "fr-CD": "fr",
    "fr-CF": "fr",
    "fr-CG": "fr",
    "fr-CH": "fr",
    "fr-CI": "fr",
    "fr-CM": "fr",
    "fr-DJ": "fr",
    "fr-DZ": "fr",
    "fr-FR": "fr-FR",
    "fr-GA": "fr",
    "fr-GF": "fr",
    "fr-GN": "fr",
    "fr-GP": "fr",
    "fr-GQ": "fr",
    "fr-HT": "fr",
    "fr-KM": "fr",
    "fr-LU": "fr",
    "fr-MA": "fr",
    "fr-MC": "fr",
    "fr-MF": "fr",
    "fr-MG": "fr",
    "fr-ML": "fr",
    "fr-MQ": "fr",
    "fr-MR": "fr",
    "fr-MU": "fr",
    "fr-NC": "fr",
    "fr-NE": "fr",
    "fr-PF": "fr",
    "fr-PM": "fr",
    "fr-RE": "fr",
    "fr-RW": "fr",
    "fr-SC": "fr",
    "fr-SN": "fr",
    "fr-SY": "fr",
    "fr-TD": "fr",
    "fr-TG": "fr",
    "fr-TN": "fr",
    "fr-VU": "fr",
    "fr-WF": "fr",
    "fr-YT": "fr",
    "fy": "fy",
    "fy-NL": "fy",
    "ga": "ga",
    "ga-IE": "ga",
    "gd": "gd",
    "gd-GB": "gd",
    "gl": "gl",
    "gl-ES": "gl",
    "gu": "gu",
    "gu-IN": "gu",
    "gv": "gv",
    "gv-IM": "gv",
    "ha": "ha",
    "ha-GH": "ha",
    "ha-NE": "ha",
    "ha-NG": "ha",
    "haw": "haw",
    "haw-US": "haw",
    "he": "iw",
    "he-IL": "iw",
    "hi": "hi",
    "hi-IN": "hi",
    "hr": "hr",
    "hr-BA": "hr",
    "hr-HR": "hr",
    "hu": "hu",
    "hu-HU": "hu",
    "hy": "hy",
    "hy-AM": "hy",
    "id": "id",
    "id-ID": "id",
    "ig": "ig",
    "ig-NG": "ig",
    "ii": "ii",
    "ii-CN": "ii",
    "is": "is",
    "is-IS": "is",
    "it": "it",
    "it-CH": "it",
    "it-IT": "it",
    "it-SM": "it",
    "it-VA": "it",
    "ja": "ja",
    "ja-JP": "ja",
    "ka": "ka",
    "ka-GE": "ka",
    "kk": "kk",
    "kk-KZ": "kk",
    "kl": "kl",
    "kl-GL": "kl",
    "km": "km",
    "km-KH": "km",
    "kn": "kn",
    "kn-IN": "kn",
    "ko": "ko",
    "ko-KP": "ko",
    "ko-KR": "ko",
    "ks": "ks",
    "ks-IN": "ks",
    "kw": "kw",
    "kw-GB": "kw",
    "ky": "ky",
    "ky-KG": "ky",
    "lb": "lb",
    "lb-LU": "lb",
    "lg": "lg",
    "lg-UG": "lg",
    "ln": "ln",
    "ln-AO": "ln",
    "ln-CD": "ln",
    "ln-CF": "ln",
    "ln-CG": "ln",
    "lo": "lo",
    "lo-LA": "lo",
    "lt": "lt",
    "lt-LT": "lt",
    "lu": "lu",
    "lu-CD": "lu",
    "lv": "lv",
    "lv-LV": "lv",
    "mg": "mg",
    "mg-MG": "mg",
    "mk": "mk",
    "mk-MK": "mk",
    "ml": "ml",
    "ml-IN": "ml",
    "mn": "mn",
    "mn-MN": "mn",
    "mr": "mr",
    "mr-IN": "mr",
    "ms": "ms",
    "ms-BN": "ms",
    "ms-MY": "ms",
    "ms-SG": "ms",
    "mt": "mt",
    "mt-MT": "mt",
    "my": "my",
    "my-MM": "my",
    "nb": "no",
    "nb-NO": "no",
    "nb-SJ": "no",
    "nd": "nd",
    "nd-ZW": "nd",
    "ne": "ne",
    "ne-IN": "ne",
    "ne-NP": "ne",
    "nl": "nl",
    "nl-AW": "nl",
    "nl-BE": "nl",
    "nl-BQ": "nl",
    "nl-CW": "nl",
    "nl-NL": "nl",
    "nl-SR": "nl",
    "nl-SX": "nl",
    "nn": "no",
    "nn-NO": "no",
    "ny": "ny",
    "om": "om",
    "om-ET": "om",
    "om-KE": "om",
    "or": "or",
    "or-IN": "or",
    "os": "os",
    "os-GE": "os",
    "os-RU": "os",
    "pa": "pa",
    "pa-Arab": "pa-Arab",
    "pa-Arab-PK": "pa-Arab",
    "pa-Guru": "pa",
    "pa-Guru-IN": "pa",
    "pl": "pl",
    "pl-PL": "pl",
    "ps": "ps",
    "ps-AF": "ps",
    "pt": "pt",
    "pt-AO": "pt",
    "pt-BR": "pt-BR",
    "pt-CH": "pt",
    "pt-CV": "pt",
    "pt-GQ": "pt",
    "pt-GW": "pt",
    "pt-LU": "pt",
    "pt-MO": "pt",
    "pt-MZ": "pt",
    "pt-PT": "pt-PT",
    "pt-ST": "pt",
    "pt-TL": "pt",
    "qu": "qu",
    "qu-BO": "qu",
    "qu-EC": "qu",
    "qu-PE": "qu",
    "rm": "rm",
    "rm-CH": "rm",
    "rn": "rn",
    "rn-BI": "rn",
    "ro": "ro",
    "ro-MD": "ro",
    "ro-RO": "ro",
    "ru": "ru",
    "ru-BY": "ru",
    "ru-KG": "ru",
    "ru-KZ": "ru",
    "ru-MD": "ru",
    "ru-RU": "ru",
    "ru-UA": "ru",
    "rw": "rw",
    "rw-RW": "rw",
    "se": "se",
    "se-FI": "se",
    "se-NO": "se",
    "se-SE": "se",
    "sg": "sg",
    "sg-CF": "sg",
    "si": "si",
    "si-LK": "si",
    "sk": "sk",
    "sk-SK": "sk",
    "sl": "sl",
    "sl-SI": "sl",
    "sn": "sn",
    "sn-ZW": "sn",
    "so": "so",
    "so-DJ": "so",
    "so-ET": "so",
    "so-KE": "so",
    "so-SO": "so",
    "sq": "sq",
    "sq-AL": "sq",
    "sq-MK": "sq",
    "sq-XK": "sq",
    "sr": "sr",
    "sr-Cyrl": "sr",
    "sr-Cyrl-BA": "sr",
    "sr-Cyrl-ME": "sr",
    "sr-Cyrl-RS": "sr",
    "sr-Cyrl-XK": "sr",
    "sr-Latn": "sr",
    "sr-Latn-BA": "sr",
    "sr-Latn-ME": "sr",
    "sr-Latn-RS": "sr",
    "sr-Latn-XK": "sr",
    "sv": "sv",
    "sv-AX": "sv",
    "sv-FI": "sv",
    "sv-SE": "sv",
    "sw": "sw",
    "sw-CD": "sw",
    "sw-KE": "sw",
    "sw-TZ": "sw",
    "sw-UG": "sw",
    "ta": "ta",
    "ta-IN": "ta",
    "ta-LK": "ta",
    "ta-MY": "ta",
    "ta-SG": "ta",
    "te": "te",
    "te-IN": "te",
    "tg": "tg",
    "tg-TJ": "tg",
    "th": "th",
    "th-TH": "th",
    "ti": "ti",
    "ti-ER": "ti",
    "ti-ET": "ti",
    "to": "to",
    "to-TO": "to",
    "tr": "tr",
    "tr-CY": "tr",
    "tr-TR": "tr",
    "tt": "tt",
    "tt-RU": "tt",
    "ug": "ug",
    "ug-CN": "ug",
    "uk": "uk",
    "uk-UA": "uk",
    "ur": "ur",
    "ur-IN": "ur",
    "ur-PK": "ur",
    "uz": "uz",
    "uz-Arab": "uz",
    "uz-Arab-AF": "uz",
    "uz-Cyrl": "uz",
    "uz-Cyrl-UZ": "uz",
    "uz-Latn": "uz",
    "uz-Latn-UZ": "uz",
    "vi": "vi",
    "vi-VN": "vi",
    "wo": "wo",
    "wo-SN": "wo",
    "xh": "xh",
    "yi": "yi",
    "yi-001": "yi",
    "yo": "yo",
    "yo-BJ": "yo",
    "yo-NG": "yo",
    "yue": "yue",
    "yue-Hans": "yue",
    "yue-Hans-CN": "yue",
    "yue-Hant": "yue",
    "yue-Hant-HK": "yue",
    "zh": "zh-CN",
    "zh-Hans": "zh-CN",
    "zh-Hans-CN": "zh-CN",
    "zh-Hans-HK": "zh-CN",
    "zh-Hans-MO": "zh-CN",
    "zh-Hans-SG": "zh-CN",
    "zh-Hant": "zh-TW",
    "zh-Hant-HK": "zh-TW",
    "zh-Hant-MO": "zh-TW",
    "zh-Hant-TW": "zh-TW",
    "zu": "zu",
    "zu-ZA": "zu"
  }





export function isRtl(lang) {
  return rtlLangList.includes(lang);
}

export function getRtlDir(lang) {
  return rtlLangList.includes(lang) ? "rtl" : "ltr";
}
